# Generated by Django 3.1.1 on 2020-12-10 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_auto_20201209_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='showedByUsers',
            field=models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
