# Generated by Django 3.1.1 on 2020-12-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201210_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='m_category_id',
            new_name='m_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
