# Generated by Django 3.1.1 on 2020-12-16 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201216_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='query',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
