# Generated by Django 3.1.1 on 2020-12-20 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201220_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numberOfViews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='viewd_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
