# Generated by Django 3.1.1 on 2020-12-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201223_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='viewd_at',
            field=models.DateTimeField(),
        ),
    ]
