# Generated by Django 3.1.1 on 2020-12-31 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20201231_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='viewd_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/subCategories/2020-12-31 09:16:54.902454'),
        ),
    ]
